### ISSUE TITLE
Invalid Character Error

### ISSUE THREAD

**Issue by masiamj** [kirill3333/react-avatar#4]
Looks like a great project! Unfortunately, I'm having an integration issue as follows: 

```bash
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/avatar.b9414da5.jsx') is not a valid name.
```

My integration looks as follows
```
<Avatar
    width={390}
    height={295}
    onCrop={this.onCrop}
    onClose={this.onClose}
    src={this.state.src}
/>
```

Any ideas?

**Comment by kirill3333** [comment]
@masiamj Could you provide more information such as 

- which react version do you use
- full error stack trace from browser
- value of src property ```this.state.src```

Thank you

**Comment by masiamj** [comment]
Thanks for your quick response!

Here's the info:

**React Version:**
Using create-react-app with React version 16.0.0

**Stacktrace:**
DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/avatar.b9414da5.jsx') is not a valid name.
    at HTMLDocument.createElement (<anonymous>:1:1545)
    at createElement (http://localhost:3001/static/js/bundle.js:44589:36)
    at createInstance (http://localhost:3001/static/js/bundle.js:55447:22)
    at completeWork (http://localhost:3001/static/js/bundle.js:49455:31)
    at completeUnitOfWork (http://localhost:3001/static/js/bundle.js:51020:18)
    at performUnitOfWork (http://localhost:3001/static/js/bundle.js:51119:14)
    at workLoop (http://localhost:3001/static/js/bundle.js:51221:28)
    at HTMLUnknownElement.callCallback (http://localhost:3001/static/js/bundle.js:39838:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3001/static/js/bundle.js:39877:16)
    at invokeGuardedCallback (http://localhost:3001/static/js/bundle.js:39734:27)
    at performWork (http://localhost:3001/static/js/bundle.js:51339:7)
    at scheduleUpdateImpl (http://localhost:3001/static/js/bundle.js:51724:19)
    at scheduleUpdate (http://localhost:3001/static/js/bundle.js:51663:12)
    at Object.enqueueSetState (http://localhost:3001/static/js/bundle.js:48185:7)

**Source:**
https://pbs.twimg.com/profile_images/839721704163155970/LI_TRk1z_400x400.jpg

**Comment by kirill3333** [comment]
@masiamj how do you import component ? with ```import``` or with ```require``` ?

**Comment by masiamj** [comment]
Using import as such:

```bash
import Avatar from 'react-avatar-edit'
```

**Comment by masiamj** [comment]
@kirill3333 Any thoughts?

**Comment by kirill3333** [comment]
@masiamj I've tried to reproduce but I can't ☹️
May be you could provide working example ?

**Comment by kirill3333** [comment]
@masiamj could you try last version 0.5.8 where I've added prebuilded version

**Comment by masiamj** [comment]
@kirill3333 You're a champion- working great!
